sonar.projectKey=tomaslopez8991_SistemaGastos
sonar.organization=tomaslopez8991
sonar.projectName=SistemaGastos
sonar.projectVersion=1.0

sonar.exclusions=\
  **/wwwroot/lib/**,\
  **/Migrations/**,\
  **/obj/**,\
  **/bin/**

sonar.coverage.exclusions=\
  **/Program.cs,\
  **/Migrations/**,\
  **/*ViewModel.cs,\
  **/*Dto.cs
