name: sistemagastos

services:
  webapi:
    image: sistemagastos-app
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=SistemaGastos;User=sa;Password=TuPasswordSuperSeguro123!;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuPasswordSuperSeguro123!
    ports:
      - "1434:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata:
